=== inf22tig06/inf22tig06/ProjetoTecInt/xml/animal_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="animais">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="animal" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nome" type="xs:string"/>
                            <xs:element name="especie" type="xs:string"/>
                            <xs:element name="idade" type="xs:positiveInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== inf22tig06/inf22tig06/ProjetoTecInt/xml/animais.xml
<?xml version="1.0" encoding="UTF-8"?>
<animais xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="animal_schema.xsd">

    <animal>
        <nome>Gato</nome>
        <especie>Felis catus</especie>
        <idade>5</idade>
    </animal>

    <animal>
        <nome>Cachorro</nome>
        <especie>Canis lupus familiaris</especie>
        <idade>3</idade>
    </animal>

    <animal>
        <nome>PÃ¡ssaro</nome>
        <especie>Aves</especie>
        <idade>1</idade>
    </animal>

</animais>
